### ISSUE TITLE
I can't connect to the ftp server

### ISSUE THREAD

**Issue by Sv9t** [melmorabity/ansible-ftp#4]
This is playbook:
```yml
---
- name: CREATE BACKUP SERVERS
  hosts: all
  gather_facts: no
  become: yes

  tasks:
  - name: CONNECT FTP
    local_action:
      module: ftp
      host: 192.168.1.1
      user: admin
      password: 123456
      src: /home/ansible/create_backup/tmp
      dest: /
      direction: pull
```

This is error log:
```
[ansible@Ansible create_backup]$ ansible-playbook -l host01 ftp.yml --ask-vault-pass -vvvvv
Using /home/ansible/create_backup/ansible.cfg as config file
Vault password:
Loading callback plugin default of type stdout, v2.0 from /usr/lib/python2.6/site-packages/ansible/plugins/callback/__init__.pyc

PLAYBOOK: ftp.yml *********************************************************************************************************************************************************************************
1 plays in ftp.yml

PLAY [CREATE BACKUP SERVERS] *****************************************************************************************************************************************************
META: ran handlers

TASK [CONNECT FTP] ********************************************************************************************************************************************************************************
task path: /home/ansible/create_backup/ftp.yml:9
fatal: [host01]: FAILED! => {
    "failed": true,
    "msg": "Could not find imported module support code for ftp.  Looked for either BOOLEANS.py or convert_bool.py"
}
        to retry, use: --limit @/home/ansible/create_backup/ftp.retry

PLAY RECAP ****************************************************************************************************************************************************************************************
host01                    : ok=0    changed=0    unreachable=0    failed=1
```

This is ansible version:
```
> ansible --version
ansible 2.3.0.0
  config file = /home/ansible/create_backup/ansible.cfg
  configured module search path = [u'/usr/share/ansible/modules']
  python version = 2.6.6 (r266:84292, Aug 18 2016, 15:13:37) [GCC 4.4.7 20120313 (Red Hat 4.4.7-17)]
```

I copied the module ftp.py to the directory /usr/share/ansible/modules/
Please help, what could be the problem?
