### ISSUE TITLE
Cannot connect to secure FTP server, says login incorrect

### ISSUE THREAD

**Issue by ZillaG** [melmorabity/ansible-ftp#6]
I have the following Ansible task

```
- name: Download artifact
  block:
  - name: "Download {{ rel_path }}"
    ftp:
      host: "sftp.company.com"
      user: "{{ sftp_user }}"
      password: "{{ sftp_password }}"
      src: "/devops/exa-3rdparty/{{ rel_path }}"
      dest: "/tmp"
      direction: pull
      timeout: 60
      protocol: ftps
    delegate_to: localhost
    register: download_st
```
But get the following, even though I know that I have the correct credentials
```
The full traceback is:
  File "/var/folders/kb/mk006j312mz2nyxbxd66gmth9fk800/T/ansible_ftp_payload_12u2ey9r/ansible_ftp_payload.zip/ansible/modules/ftp.py", line 544, in main
  File "/var/folders/kb/mk006j312mz2nyxbxd66gmth9fk800/T/ansible_ftp_payload_12u2ey9r/ansible_ftp_payload.zip/ansible/modules/ftp.py", line 169, in wrapper
  File "/var/folders/kb/mk006j312mz2nyxbxd66gmth9fk800/T/ansible_ftp_payload_12u2ey9r/ansible_ftp_payload.zip/ansible/modules/ftp.py", line 496, in _ftp_connect
  File "/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ftplib.py", line 746, in login
    return super().login(user, passwd, acct)
  File "/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ftplib.py", line 414, in login
    resp = self.sendcmd('PASS ' + passwd)
  File "/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ftplib.py", line 281, in sendcmd
    return self.getresp()
  File "/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ftplib.py", line 254, in getresp
    raise error_perm(resp)
fatal: [10.227.26.97]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "attributes": null,
            "backup": false,
            "dest": "/tmp",
            "direction": "pull",
            "ftp_mode": "passive",
            "group": null,
            "host": "stp.company.com",
            "interval": 1,
            "mode": null,
            "owner": null,
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port": 21,
            "protocol": "ftps",
            "retries": 3,
            "selevel": null,
            "serole": null,
            "setype": null,
            "seuser": null,
            "src": "/devops/exa-3rdparty/7z/7z2107-x64.exe",
            "timeout": 60,
            "tmp_dest": null,
            "unsafe_writes": false,
            "user": "devops"
        }
    },
    "msg": "Unable to connect to FTP server: 530 Login incorrect."
```
If I connect to a non-SFTP server it works.
